/**
 * Phase 2B — server-only Razorpay Orders API adapter.
 *
 * Talks to Razorpay's REST endpoint directly via the built-in `fetch`
 * rather than adding the official Razorpay Node SDK as a dependency —
 * Order creation is a single authenticated JSON POST
 * (docs/RAZORPAY_GUIDE.md Section 11), so a fetch-based adapter is the
 * smallest reliable implementation consistent with docs/PHASE_PLAN.md
 * Section 6.4 ("server-side Razorpay adapter") and CLAUDE.md's "do not add
 * unnecessary frameworks" rule. Only Order creation is implemented — no
 * payments.fetch, captures, refunds, webhook API, or Checkout.
 *
 * Authenticates using HTTP Basic Auth with
 * `RAZORPAY_KEY_ID:RAZORPAY_KEY_SECRET`, obtained exclusively from the
 * validated Phase 2A `getRazorpayEnv()` accessor
 * (`lib/config/razorpay-env.ts`). This module never reads `process.env`
 * directly, never accepts a caller-supplied credential, and never returns
 * or logs the Key Secret. `import "server-only"` makes this a structural,
 * build-time-enforced guarantee (same pattern as
 * `lib/supabase/server.ts`).
 */
import "server-only";

import { getRazorpayEnv } from "@/lib/config/razorpay-env";

const RAZORPAY_ORDERS_ENDPOINT = "https://api.razorpay.com/v1/orders";

/**
 * Razorpay's Create Order API rejects a `receipt` longer than this with
 * HTTP 400 — confirmed by a real Test Mode manual verification (Phase 2B
 * correction; see handoffs/PHASE-2-HANDOFF.md). Exported so the caller's
 * receipt generator can be tested against the same authoritative limit.
 */
export const RAZORPAY_RECEIPT_MAX_LENGTH = 40;

/**
 * Thrown when the caller's `receipt` violates Razorpay's provider contract
 * (empty, or longer than `RAZORPAY_RECEIPT_MAX_LENGTH`). This is a
 * pre-flight guard: the check runs BEFORE any network call, so an invalid
 * receipt can never reach Razorpay. This is deliberately a different error
 * from `RazorpayOrderRejectedError`/`RazorpayOrderAmbiguousError` — no
 * request was ever sent, so the caller must not mark the attempt
 * `FAILED_OBSERVED` (that implies a real provider rejection) or treat the
 * outcome as ambiguous (nothing indeterminate happened).
 */
export class RazorpayReceiptInvalidError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RazorpayReceiptInvalidError";
  }
}

export interface CreateRazorpayOrderInput {
  /** Integer smallest-currency subunits — already validated/persisted by the caller. Never multiplied again here. */
  readonly amountSubunits: number;
  readonly currency: string;
  /**
   * The caller's already-generated, already-persisted stable receipt
   * (PAYATT-003). Never generated by this module. Must be non-empty and
   * at most `RAZORPAY_RECEIPT_MAX_LENGTH` characters — enforced below
   * before any network call.
   */
  readonly receipt: string;
}

function assertValidReceipt(receipt: string): void {
  if (typeof receipt !== "string" || receipt.length === 0) {
    throw new RazorpayReceiptInvalidError(
      "Razorpay receipt must be a non-empty string.",
    );
  }
  if (receipt.length > RAZORPAY_RECEIPT_MAX_LENGTH) {
    throw new RazorpayReceiptInvalidError(
      `Razorpay receipt exceeds the provider's ${RAZORPAY_RECEIPT_MAX_LENGTH}-character limit (received ${receipt.length} characters).`,
    );
  }
}

export interface RazorpayOrderResult {
  readonly razorpayOrderId: string;
  readonly razorpayOrderStatus: string;
}

/**
 * A definite provider rejection — Razorpay received and evaluated the
 * request, then refused it (e.g. malformed request, authentication
 * failure). The caller may safely treat this as "no Order was created"
 * (docs/RAZORPAY_GUIDE.md Section 38.1/39 "Order Creation").
 */
export class RazorpayOrderRejectedError extends Error {
  readonly httpStatus: number;
  readonly safeErrorCode: string | undefined;

  constructor(
    httpStatus: number,
    safeErrorCode: string | undefined,
    message: string,
  ) {
    super(message);
    this.name = "RazorpayOrderRejectedError";
    this.httpStatus = httpStatus;
    this.safeErrorCode = safeErrorCode;
  }
}

/**
 * An ambiguous outcome — a network failure, a timeout, an unparseable
 * response, or a provider-side (5xx) error — where whether an Order was
 * actually created cannot be determined from this response alone. The
 * caller must NOT retry with a new receipt (docs/RAZORPAY_GUIDE.md Section
 * 39 "Order Creation", PAYATT-004) and must not assume either success or
 * failure.
 */
export class RazorpayOrderAmbiguousError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RazorpayOrderAmbiguousError";
  }
}

type FetchLike = typeof fetch;

function extractSafeErrorCode(body: unknown): string | undefined {
  if (
    typeof body === "object" &&
    body !== null &&
    "error" in body &&
    typeof (body as { error?: unknown }).error === "object" &&
    (body as { error?: unknown }).error !== null
  ) {
    const code = (body as { error: { code?: unknown } }).error.code;
    return typeof code === "string" ? code : undefined;
  }
  return undefined;
}

function extractStringField(body: unknown, field: string): string | undefined {
  if (typeof body === "object" && body !== null && field in body) {
    const value = (body as Record<string, unknown>)[field];
    return typeof value === "string" ? value : undefined;
  }
  return undefined;
}

/**
 * Creates one Razorpay Test Mode Order using the caller's already-validated
 * amount/currency/receipt (PAYATT-001, PAYATT-003). Never generates its own
 * receipt and never derives amount/currency from anything but the explicit
 * `input` argument the caller controls.
 *
 * Throws `RazorpayReceiptInvalidError` synchronously, before any network
 * call, if `input.receipt` is empty or longer than
 * `RAZORPAY_RECEIPT_MAX_LENGTH` — a defense-in-depth guard against ever
 * sending Razorpay a receipt it is guaranteed to reject.
 *
 * `fetchImpl` defaults to the global `fetch` and exists only so tests can
 * inject a fake implementation — no automated test performs a real network
 * call or depends on real Razorpay credentials.
 */
export async function createRazorpayOrder(
  input: CreateRazorpayOrderInput,
  fetchImpl: FetchLike = fetch,
): Promise<RazorpayOrderResult> {
  assertValidReceipt(input.receipt);

  const { keyId, keySecret } = getRazorpayEnv();
  const basicAuth = Buffer.from(`${keyId}:${keySecret}`).toString("base64");

  let response: Response;
  try {
    response = await fetchImpl(RAZORPAY_ORDERS_ENDPOINT, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Basic ${basicAuth}`,
      },
      body: JSON.stringify({
        amount: input.amountSubunits,
        currency: input.currency,
        receipt: input.receipt,
      }),
    });
  } catch {
    // Network-level failure (DNS, connection reset, timeout, abort, etc.)
    // — the request outcome is unknown, not "failed".
    throw new RazorpayOrderAmbiguousError(
      "Could not reach Razorpay to create the Order (network failure). The outcome is unknown; do not retry with a new receipt.",
    );
  }

  if (response.status >= 500) {
    throw new RazorpayOrderAmbiguousError(
      `Razorpay returned a server error (HTTP ${response.status}) creating the Order. The outcome is unknown; do not retry with a new receipt.`,
    );
  }

  let body: unknown;
  try {
    body = await response.json();
  } catch {
    throw new RazorpayOrderAmbiguousError(
      "Razorpay's Order-creation response could not be parsed. The outcome is unknown; do not retry with a new receipt.",
    );
  }

  if (!response.ok) {
    throw new RazorpayOrderRejectedError(
      response.status,
      extractSafeErrorCode(body),
      `Razorpay rejected the Order-creation request (HTTP ${response.status}).`,
    );
  }

  const razorpayOrderId = extractStringField(body, "id");
  const razorpayOrderStatus = extractStringField(body, "status");
  if (!razorpayOrderId || !razorpayOrderStatus) {
    throw new RazorpayOrderAmbiguousError(
      "Razorpay's Order-creation response did not contain the expected id/status fields.",
    );
  }

  return { razorpayOrderId, razorpayOrderStatus };
}
